
# This file was *autogenerated* from the file fig-gradient-06.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50)# Ligne de gradient
reset()

#var('x,y,z')
#f = x^2+y^2-z^2
#G = implicit_plot3d(f,(x,-2,2),(y,-2,2),(z,-2,2),contours=[-1,0,1],region=lambda x,y,z: x<=0.2 or y>=0.2)
#G.show()


var('x,y,z')
f = x**_sage_const_2 +y**_sage_const_2 -z**_sage_const_2 
G = implicit_plot3d(f,(x,-_sage_const_2 ,_sage_const_2 ),(y,-_sage_const_2 ,_sage_const_2 ),(z,-_sage_const_2 ,_sage_const_2 ),contours=[_sage_const_0 ],plot_points=_sage_const_50 , color='darkkhaki')
G.show()

#G.save('fig-gradient-06.png')

